@hostname=localhost
@httpPort=5132
@httpsPort=7289

### List (HTTP)
GET http://{{hostname}}:{{httpPort}}/customers
Accept: application/json

###
@customerId=1f1efc05-7e47-48b8-8fa4-6046f9cb2524
GET http://{{hostname}}:{{httpPort}}/customers/{{customerId}}
Accept: application/json

### Create (HTTPS) – if running the https profile
POST https://{{hostname}}:{{httpsPort}}/customers
Accept: application/json
Content-Type: application/json

{
  "companyName": "NimblePros2ehhhw",
  "emailAddress": "test@test.com"
}

### Update (HTTP)
@customerIdToUpdate=1f1efc05-7e47-48b8-8fa4-6046f9cb2524
PUT http://{{hostname}}:{{httpPort}}/customers/{{customerIdToUpdate}}
Accept: application/json
Content-Type: application/json

{
  "companyName": "gwqgewqewqeqweqw"
}

### Delete (HTTP)
@customerIdToDelete=2018e8cd-7668-458c-a489-4b8a9406ff16
DELETE http://{{hostname}}:{{httpPort}}/customers/{{customerIdToDelete}}
Accept: application/json

### Coffee (check the route name – likely /brewcoffee)
GET http://{{hostname}}:{{httpPort}}/brewcoffee
