@hostname=localhost
@port=5132
@host={{hostname}}:{{port}}

GET http://{{host}}/customers
Accept: application/json


###

@customerId=25c9868f-a724-4257-9758-09e372116936 
GET http://{{host}}/customers/{{customerId}}
Accept: application/json

###


POST http://{{host}}/customers
Accept: application/json
Content-Type: application/json

{
  "companyName": "NimblePros"
}


@customerIdToUpdate=25c9868f-a724-4257-9758-09e372116936 
PUT http://{{host}}/customers/{{customerIdToUpdate}}
Accept: application/json
Content-Type: application/json

{
  "companyName": "NimblePros"
}
###

@customerIdToDelete=25c9868f-a724-4257-9758-09e372116936 
DELETE http://{{host}}/customers/{{customerIdToDelete}}
Accept: application/json

###

GET http://{{host}}/brewcofee

