// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ESolutions.Customers.Web.Customers;

#nullable disable

namespace NimblePros.Customers.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ESolutions.Customers.Web.Customers.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CompanyName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("EmailAddress")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("ESolutions.Customers.Web.Customers.Project", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("TEXT");

                b.Property<string>("ProjectName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.ToTable("Project");
            });

            modelBuilder.Entity("ESolutions.Customers.Web.Customers.Project", b =>
            {
                b.HasOne("ESolutions.Customers.Web.Customers.Customer", null)
                    .WithMany("Projects")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("ESolutions.Customers.Web.Customers.Customer", b =>
            {
                b.Navigation("Projects");
            });
#pragma warning restore 612, 618
        }
    }
}
